// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuPglaIhRFIxThtha4p7Iy0g9WbKwCOiE',
    appId: '1:635829394211:web:f00f9d6576a275b7d18a96',
    messagingSenderId: '635829394211',
    projectId: 'digitaljournal-14768',
    authDomain: 'digitaljournal-14768.firebaseapp.com',
    storageBucket: 'digitaljournal-14768.appspot.com',
    measurementId: 'G-WBHBNJHLZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Y5Yztc9tr-chHfJ4K2syMJYQRLZcG5M',
    appId: '1:635829394211:android:02ee12993aa3d317d18a96',
    messagingSenderId: '635829394211',
    projectId: 'digitaljournal-14768',
    storageBucket: 'digitaljournal-14768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy35r21fjsOB39m01SZH7hQhjpswwsw-I',
    appId: '1:635829394211:ios:ee265d35409d01e1d18a96',
    messagingSenderId: '635829394211',
    projectId: 'digitaljournal-14768',
    storageBucket: 'digitaljournal-14768.appspot.com',
    iosClientId: '635829394211-f4rg6bl2n2tj7di5bhfcs03djahd3jur.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy35r21fjsOB39m01SZH7hQhjpswwsw-I',
    appId: '1:635829394211:ios:e952d915b61e0cefd18a96',
    messagingSenderId: '635829394211',
    projectId: 'digitaljournal-14768',
    storageBucket: 'digitaljournal-14768.appspot.com',
    iosClientId: '635829394211-kakc835j0qnv6gdkci4enmoi4cul12l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
