// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgh7hAm6i63DYkJrz7fM12kl8ykrJk1g',
    appId: '1:835174935408:web:a87e863592078c4d77fdb5',
    messagingSenderId: '835174935408',
    projectId: 'digital-journal-389119',
    authDomain: 'digital-journal-389119.firebaseapp.com',
    storageBucket: 'digital-journal-389119.appspot.com',
    measurementId: 'G-48MX3MYRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQ7XjUpNihcTaz-yobGHPCzZSAeaOCmc',
    appId: '1:835174935408:android:4ea1592284fbe4f877fdb5',
    messagingSenderId: '835174935408',
    projectId: 'digital-journal-389119',
    storageBucket: 'digital-journal-389119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0NLjEgNLWSmaj1-Wpf1DvDd43WDXmAI',
    appId: '1:835174935408:ios:9b73aa884b54231077fdb5',
    messagingSenderId: '835174935408',
    projectId: 'digital-journal-389119',
    storageBucket: 'digital-journal-389119.appspot.com',
    iosClientId: '835174935408-aiu0kautpkrrv37v73ko73rktd3jhsg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
