name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: cd app && flutter pub get

      - name: Build APK
        run: cd app && flutter build apk --release

      - name: Run tests
        run: cd app && flutter test

      - name: Analyze code
        run: cd app && flutter analyze
